# Generated by Django 2.2.1 on 2019-05-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='客户名')),
                ('post', models.CharField(max_length=20, verbose_name='职位')),
                ('body', models.CharField(max_length=500, verbose_name='意见')),
            ],
            options={
                'verbose_name': '客户意见',
                'verbose_name_plural': '客户意见',
            },
        ),
        migrations.CreateModel(
            name='Anli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('body', models.CharField(max_length=500, verbose_name='内容')),
                ('img', models.ImageField(upload_to='abs', verbose_name='图片')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
