# Generated by Django 2.2.1 on 2019-05-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='客户名')),
                ('post', models.CharField(max_length=20, verbose_name='职位')),
                ('body', models.CharField(max_length=500, verbose_name='意见')),
                ('img', models.ImageField(upload_to='abs')),
            ],
            options={
                'verbose_name': '客户意见',
                'verbose_name_plural': '客户意见',
            },
        ),
        migrations.CreateModel(
            name='Anli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('body', models.CharField(max_length=500, verbose_name='内容')),
                ('img', models.ImageField(upload_to='abs', verbose_name='图片')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads')),
            ],
            options={
                'verbose_name': '图片集',
                'verbose_name_plural': '图片集',
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='项目名称')),
                ('body', models.CharField(max_length=500, verbose_name='简介')),
                ('img', models.ImageField(upload_to='abs')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='公司名')),
                ('post', models.CharField(max_length=20, verbose_name='职位')),
                ('body', models.CharField(max_length=100, verbose_name='简介')),
                ('img', models.ImageField(upload_to='abs')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
            },
        ),
        migrations.CreateModel(
            name='type_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='类型')),
                ('price', models.IntegerField()),
                ('time', models.CharField(max_length=30, verbose_name='时长')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='应用名')),
                ('body', models.CharField(max_length=50, verbose_name='应用介绍')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.type_on')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
            },
        ),
        migrations.CreateModel(
            name='itemtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ittype', models.CharField(max_length=30, verbose_name='项目类型')),
                ('itm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.item')),
            ],
        ),
        migrations.CreateModel(
            name='itemimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='abs')),
                ('itimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.item')),
            ],
        ),
    ]
