# Generated by Django 2.2.1 on 2019-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='img',
            field=models.ImageField(default=None, upload_to='abs'),
            preserve_default=False,
        ),
    ]
