# Generated by Django 2.2.1 on 2019-05-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190530_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '博客文章', 'verbose_name_plural': '博客文章'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '博客评论', 'verbose_name_plural': '博客评论'},
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
